name: Push-to-EC2

# Trigger deployment only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the main branch
      - name: Checkout the files
        uses: actions/checkout@v2

      # Deploy to the server by syncing the files
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Run commands on the server via SSH
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install apache if necessary
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Clean the target directory before copying new files
            sudo rm -rf /var/www/whiskylaravel/*
            sudo rm -rf /var/www/whiskylaravel/.*
            
            # Copy files from the home directory to the target
            sudo cp -r ~/github/workspace/* /var/www/whiskylaravel/
            
            # Set correct permissions
            sudo chown -R www-data:www-data /var/www/whiskylaravel
            sudo chmod -R 755 /var/www/whiskylaravel

            # Restart Apache to apply changes
            sudo systemctl restart apache2
